# Generated by Django 4.2.7 on 2023-11-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_reason',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer_name',
            field=models.CharField(max_length=150),
        ),
    ]
