# Generated by Django 4.2.7 on 2023-11-21 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_referral_referral_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='referral_documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
